language: node_js
node_js:
  - 16

sudo: required
services:
  - docker

cache:
  directories:
    - docker_images

before_cache:
  - docker save -o docker_images/images.tar $(docker images -aq)

before_script:
  - docker load -i docker_images/images.tar || true

install:
  - npm install

script:
  - npm run ci

skip_cleanup: true
